### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by sagirk** [elenaparaschiv/BeastChallange-4#1]
**Code style**
- Inconsistent spacing in comments ([L7](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L7), [L15](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L15), [L23](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L23)), after control statements ([L4](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L4), [L6](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L6), [L8](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L8), [L16](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L16)), etc.
- Inconsistent indentation ([L18](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L18), [L21](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L21)). 
- Use [Airbnb's style guide](https://github.com/airbnb/javascript/tree/es5-deprecated/es5) for a consistent coding style.

**Code reuse** 
- Reuse previously declared variables where it aids readibility ([L25](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L25) can be reused in [L26](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L26), [L27](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L27)).

**Concise tests**
- [L50](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L50), [L64](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L64), [L78](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L78) are unnecessary since they don't contribute to the tests. [L91](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L91), [L92](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L92), [L93](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L93), on the other hand, are useful (you could further clean this last test by keeping only what is necessary).
- Why use a cryptic var name when the more clear version is just 4 more chars? ([L83](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L83)).

**Missing test**
- There's no test to check if the function throws TypeError under right conditions (for [L19](https://github.com/elenaparaschiv/Libraries-out-of-order/blob/master/librarySystem.html#L19)).

Great job! Your logic behind the function is sound! 👍

**Comment by elenaparaschiv** [comment]
Fixed it. And thanks for recalling the styling guide. I missed to see it and will use it from now on.

**Comment by sagirk** [comment]
Posting a link to the review in the main comment thread so others can benefit from it too. This is helpful because many of us have problems with the same things.
